### PR TITLE
Create standardized PositionType class

### PR DESCRIPTION
**Pull request by DriesDeprest**
PR related to: https://github.com/PySport/kloppy/issues/331.

I've replaced the Position with the 'standardized' PositionType class. I've refactored the StatsBomb deserializer and tests to work with the proposed changes.

I'm awaiting approval by @JanVanHaaren / @koenvo of the proposed implementation in this PR, before updating other serializers.

### CODE REVIEW

**Comment by koenvo** [comment]
Akkoord

**Comment by DriesDeprest** [comment]
@koenvo let me know if you have feedback on the implementation!

**Comment by koenvo** [comment]
@JanVanHaaren do you think it matters that we lose the provider specific `position_id`?

**Comment by JanVanHaaren** [comment]
> @JanVanHaaren do you think it matters that we lose the provider specific `position_id`?

I don't think so. We're losing provider-specific information in other areas as well.

**Comment by DriesDeprest** [comment]
@koenvo any other feedback or changes required to get this approved?

**Comment by koenvo** [comment]
Nope. LGTM. Thanks!

**Review by koenvo — APPROVED** [review]

**Comment by koenvo** [comment]
Hmm was merging PRs but seems there's a merge conflict. Are you able to resolve it, please?

**Pull request merged**
