### PR TITLE
Redo of #PR215

### PR DESCRIPTION
**Pull request by UnravelSports**
Because I made a mess of PR https://github.com/PySport/kloppy/pull/215, here is a clean attempt. 
It includes updated jsonl loader without with open(), Dries' minor changes to IDs as proposed in https://github.com/PySport/kloppy/commit/277a7143566df9f05cef5b1d66a353cadcb0f4ba and updated event_factory.

### CODE REVIEW

**Comment by JanVanHaaren** [comment]
Thanks, @UnravelSports! The changes to the SkillCorner deserializer look good to me.

Could you please fix the [code formatting](https://kloppy.pysport.org/contributing/#code-formatting)? I suspect that the formatting changes to the event data deserializers were unintentional.

**Comment by JanVanHaaren** [comment]
@UnravelSports I've managed to make the necessary changes myself. 😊

**Review by JanVanHaaren — APPROVED** [review]

**Comment by UnravelSports** [comment]
@JanVanHaaren for future reference, what formatting was wrong? Because I did run black on all the files, so kinda curious where it went wrong

Thanks for fixing it and approving of the changes!

**Comment by JanVanHaaren** [comment]
> @JanVanHaaren for future reference, what formatting was wrong? Because I did run black on all the files, so kinda curious where it went wrong

Good question. I suspect that you're using a different version of `black` that has slightly different default preferences, but I'm  not entirely sure.

**Comment by UnravelSports** [comment]
Good point, I'll update :)

**Pull request merged**
