### PR TITLE
Tracab Meta added (V4)

### PR DESCRIPTION
**Pull request by UnravelSports**
I've added an option for reading yet another version of the Tracab Meta data (as requested by here https://github.com/PySport/kloppy/discussions/352)

My main concern is the ever growing amount of random Tracab Meta file configurations, but for now this implementation should hold. Not sure how to approach this other than wait for issues to be raised...

It first checks if there is a "match" attribute in the meta_data and if not it will check a key I have yet only seen in this new version of the meta data (`Phase1StartFrame`). Additionally there are some small additions to make the create_team function a bit more flexible because some tags have slightly changed in this version. `<Player>` became `<item>` and `<TeamId>` became `<TeamID>` (same for player ids).

I've also added new tests.

### CODE REVIEW

**Comment by UnravelSports** [comment]
The tests seem to fail at a random file I didn't touch?

**Comment by Alek050** [comment]
> The tests seem to fail at a random file I didn't touch?

Was just sniffing around this issue. Seems like the git actions fail on the formatting of `kloppy/infra/serializers/event/sportec/deserializer.py`. I am guessing that your local formatting settings (maybe with black?) are different from the ones on git, but not sure though.

**Comment by UnravelSports** [comment]
I see my commit contains that file, in a slightly different format. Weird 🤷‍♀️

**Comment by UnravelSports** [comment]
I had black version 23.3.0 instead of 22.3.0...

**Pull request merged**
