### PR TITLE
Set orientation for Metrica EPTS (#167)

### PR DESCRIPTION
**Pull request by probberechts**
**DISCLAIMER**: this is based on sample match 3 in the Metrica open data. I do not know whether this solution generalizes.

### CODE REVIEW

**Comment by koenvo** [comment]
Thanks for this PR!

@jcnunezmoreno are you able to verify this fix generalizes?

**Comment by jcnunezmoreno** [comment]
@probberechts Thanks for the PR! The problem is FIFA EPTS only defines how to structure the data but not what you can find there, this is the reason why this EPTS is related to Metrica, because is the way we export the data.

@koenvo Related to you question, we always use the keys/values for the orientation as in the sample 3, so it will generalizes for the rest of the files. But I tested on my own sample game and the orientation was not set, it contains the value "not-set", maybe a test can be added based on the sample game 3. If it works I can share with you other EPTS file (the one that is not working for me) and try to add to the test.

**Comment by probberechts** [comment]
> @probberechts Thanks for the PR! The problem is FIFA EPTS only defines how to structure the data but not what you can find there, this is the reason why this EPTS is related to Metrica, because is the way we export the data.

It is clear that this is specifically a parser for the **Metrica** EPTS format. So, then I think this PR is fine.

> But I tested on my own sample game and the orientation was not set, it contains the value "not-set", maybe a test can be added based on the sample game 3. 

There are tests included on a metadata file that has the same structure as sample game 3. I also tested it on sample game 3 and it returns the correct orientation for me (see example below). Hence, I am curious what's the difference with your sample game. 

```py
>> from kloppy import metrica
>> dataset = metrica.load_open_data(match_id="3", limit=10)
>> dataset.metadata.orientation
away-team
```

**Comment by jcnunezmoreno** [comment]
@probberechts Yeah, sorry, you are right! I was checking different field. I checked it on some games and it works good! Thanks!

**Pull request merged**
