### PR TITLE
Setup code formatting tool

### LINKED ISSUE #5: Setup code formatting tool
kloppy doesn't have any code formatting tool in place. To make sure the code will be maintainable in the long term a code formatter is needed.

Black ( https://github.com/psf/black ) might be a good option.

### PR DESCRIPTION
**Pull request by dmallory42**
**Summary of Changes**

- Installed the `black` library to run code formatting, and the `pre-commit` library to add a git hook which automatically formats changed code on `git commit` as per the `black` specification. 
- Added `.pre-commit-config.yaml` to configure `pre-commit`
- Added `pyproject.toml` which contains configuration for `black`.
- Ran `black` on the existing codebase. (this looks like a lot of changes but all are code formatting)
- Added a requirements.txt file containing the project library requirements to allow easy install via pip for development (including `black` and `pre-commit` and other libraries used in the project)

**Setup** 

Automatic code formatting on git commit has to be set up on a per-developer basis. The following steps would need to be followed:

- Install the necessary libraries by running `pip install -r requirements.txt`
- Execute `pre-commit install` to install the Git hook.
- When a `git commit` command is executed, the hook will run `black` on any changed code files.

These steps should be added to developer documentation, but I wasn't sure on the best place to put these so happy to update this based on what you think is best.

Alternatively, if auto-code format on git commit isn't wanted, the command `black .` can be executed before committing code to format code.

### CODE REVIEW

**Comment by koenvo** [comment]
Thanks for this pull request! It looks good.

Question about the pre-commit hook: when black processes the files, it pre-commit hook will fail right? So you have to re-add the changes black made and recommit. (My source: https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/)

And it's a good idea to document the setup. I think it should go in CONTRIBUTING.md in the root. Your setup notes are a good first version.

**Comment by dmallory42** [comment]
Yes, that's correct. It behaves as described in the link. Should have mentioned that! 

That sounds sensible. I'm happy to add some basic instructions to CONTRIBUTING.md and update this PR (or would you suggest that should be a separate pull request?)

**Comment by koenvo** [comment]
Please add CONTRIBUTING.md to this pull request. Looking forward to merge this as it helps others a lot when they like to contribute!

**Comment by dmallory42** [comment]
Hi, I've updated this with a CONTRIBUTING.md file - let me know if anything needs to be changed!

**Pull request merged**
