### PR TITLE
Add SkillCorner extrapolated_data.jsonl loading functionality

### PR DESCRIPTION
**Pull request by UnravelSports**
I noticed there was no support for loading `extrapolated_data.jsonl` files, only deprecated `structured_data.json` files.

As you can see in the messy commit history I've added a couple things:

- Functionality to load `jsonl` files if that file suffix is in place for `raw_data`. This functionality simply converts the json lines to a list of json objects such that it looks exactly like the `structured_data.json` files. We also rename the `timestamp` key to `time` to make it compatible with the rest of the code (that relies on the old `time` key).
- Added improved timestring parsing because the `extrapolated` files have a slightly different timestamp format. The old format is `"92:37.60"` whereas the new format would display this as `"01:32:37.60"`. The `_timestamp_from_timestring()` function can now handle both cases, converting both of these formats to the same output.
- Added an improvement to reset the time at the start of each half to 0. As mentioned in https://github.com/PySport/kloppy/issues/214 this was not implemented yet. This might be a breaking change for some people relying on timestamps, so we might have to think about how to actually implement this last part.

Finally, I would not be surprised if the tests fail because of the change in period start time...

### CODE REVIEW

**Comment by DriesDeprest** [comment]
@JanVanHaaren @koenvo what are your thoughts on the last point raised regarding the start timestamp of the second period?

What seems like a good plan to bring this work regarding supporting SkillCorners .jsonl tracking data files into kloppy while considering backwards compatibility?

**Comment by DriesDeprest** [comment]
@koenvo @UnravelSports this [commit](https://github.com/PySport/kloppy/commit/0fd9ad6a1dd116b932717da948999d0a547819ae#diff-2932ebed1fc21704c8b8f5847df9d9fef6196c1c23534746e4ed5e3f0c0b8a95) should still be applied prior to merging imo. This way we use the SkillCorner ID as the player ID in the dataset. I'd love to do it myself but I can't contribute to this PR. So can any of you guys apply the changes?

@koenvo do you know why some of the checks are failing?

**Comment by JanVanHaaren** [comment]
> @koenvo do you know why some of the checks are failing?

The checks should succeed again after merging in `master`. The issue was fixed in #231.

**Comment by JanVanHaaren** [comment]
@UnravelSports Could you please merge the `master` branch into your feature branch? Thanks!

**Comment by UnravelSports** [comment]
It seems I've made a mess out of this, I'm creating a new PR to make a clean PR 😆

**Pull request closed without merging**
