### PR TITLE
Fixing load empty values from metrica epts loader and test added

### PR DESCRIPTION
**Pull request by jcnunezmoreno**

### CODE REVIEW

**Comment by jcnunezmoreno** [comment]
Fix #162

**Comment by jcnunezmoreno** [comment]
Hi @koenvo, when is it planned to release a new version? I would like to have this fix integrated in kloppy :) 
Thanks!

**Comment by koenvo** [comment]
Thanks for this fix! I just released 3.6.1

**Comment by jcnunezmoreno** [comment]
Great!! Thank you so much!!

**Pull request merged**
