### PR TITLE
Include all event qualifiers

### PR DESCRIPTION
**Pull request by cedrickrause**
DRAFT

Pull Request for adjustments mentioned in #97.
Started with BodyPart for metrica event data.

### CODE REVIEW

**Comment by cedrickrause** [comment]
BodyPart for sportec event data also added now. However the body part is only given for shots in sportec data, so there are no body part qualifiers for passes or so.

**Comment by koenvo** [comment]
Thanks for the pull request @cedrickrause! I'm a bit busy. Will have a look at the code and your questions and respond asap

**Comment by cedrickrause** [comment]
@koenvo No worries. 
I now also added the body part qualifier for the opta event data. So all missing serializers should now have the body part qualifier. However there is none of the body part qualifiers in the example opta event f24 file, so finding a new one with them in it, would be needed to test the new behavior.
Might make sense to seperate the pass qualifiers in another pull request, as I am not sure how quickly I will get to it.

**Comment by koenvo** [comment]
Thanks Cedrick!

**Pull request merged**
